### ISSUE TITLE
memory leak on release-0.4

### ISSUE THREAD

**Issue by cospotato** [kubernetes-csi/livenessprobe#102]
The livenessprobe will create new grpc connection every request and never close it.

https://github.com/kubernetes-csi/livenessprobe/blob/9ef0206a61c12026e81271e93de1e9dd478fd0ac/cmd/main.go#L70-L73

**Comment by juliohm1978** [comment]
Coming by to confirm this is still happening, seems to be affecting the [csi-smb-driver](https://github.com/kubernetes-csi/csi-driver-smb) as well.

https://github.com/kubernetes-csi/csi-driver-smb/issues/226

**Comment by mauriciopoppe** [comment]
I see that the connection is closed in https://github.com/kubernetes-csi/livenessprobe/blob/master/cmd/livenessprobe/main.go#L67, is this problem still happening to you?

**Comment by cospotato** [comment]
> I see that the connection is closed in https://github.com/kubernetes-csi/livenessprobe/blob/master/cmd/livenessprobe/main.go#L67, is this problem still happening to you?

Hello @mauriciopoppe . Yes, it was closed in master branch. But i m using Kubernetes 1.13 which need the release-0.4 branch. Would you please pick this fix to the release-0.4 branch ?

**Comment by mauriciopoppe** [comment]
From https://kubernetes.io/releases/version-skew-policy/

> The Kubernetes project maintains release branches for the most recent three minor releases (1.23, 1.22, 1.21). Kubernetes 1.19 and newer receive approximately 1 year of patch support. Kubernetes 1.18 and older received approximately 9 months of patch support.

livenessprobe release-0.4 uses CSI Spec 0.3 which is deprecated as of https://kubernetes-csi.github.io/docs/kubernetes-changelog.html#kubernetes-117 too.

I don't think we can backport given that it's for a version of kubernetes that's no longer supported and by how huge the diff is between the latest version of this library and release-0.4, you could probably fork the library at that release and add the connection close code if this is still a problem.

**Comment by cospotato** [comment]
>  you could probably fork the library at that release and add the connection close code if this is still a problem.

@mauriciopoppe OK. Thanks for your reply.
