### ISSUE TITLE
liveness-probe is logging to stderr

### ISSUE THREAD

**Issue by dkirrane** [kubernetes-csi/livenessprobe#105]
Can `liveness-probe` be updated the not log everything to `stderr`
See issue:
https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/398

**Comment by crablab** [comment]
Just leaving a +1 on this - it's not really necessary to see "Connecting to unix..." on every log line. I think it would be better to only log actual warnings/errors to `stderr`.
