### ISSUE TITLE
Make passing Travis required for merge

### ISSUE THREAD

**Issue by saad-ali** [kubernetes-csi/livenessprobe#13]
Make passing Travis required for merge

xref https://github.com/kubernetes/test-infra/pull/9014#discussion_r209759777

/assign @sbezverk

**Comment by sbezverk** [comment]
@saad-ali to really test it that would require a k8s cluster or minikube, should I add a sort of integration test, brining k8s and then starting liveness probe?

**Comment by jsafrane** [comment]
Travis runs `go vet`, `make`, `gofmt` and `go test`, all this is great to have (and it should succeed before merge). However, I don't see any real tests. `go test` does not run anything.

So yes, let's make travis mandatory, but also let's prepare real tests. Liveness probe is a simple executable that talks to CSI driver and returns error when `Probe()` fails. All this can be tested outside of Kubernetes easily with a mock CSI driver.

**Comment by sbezverk** [comment]
@jsafrane I can add a small script to travis to start hostpath driver and liveness probe and check the result of a probe. Would it be sufficient for testing?

**Comment by jsafrane** [comment]
Yes, that's a good start. And a script that runs just the probe and no driver (-> timeout or connection refused? -> nozero exit code) should be easy too and it would cover one error case.

**Comment by spiffxp** [comment]
When you're ready to implement this, open a PR to https://github.com/kubernetes/test-infra/blob/master/prow/config.yaml

eg: for kubernetes-csi/external-attacher https://github.com/kubernetes/test-infra/blob/master/prow/config.yaml#L172-L175

**Comment by sbezverk** [comment]
@spiffxp PTAL https://github.com/kubernetes/test-infra/pull/9051
