### ISSUE TITLE
armv7 images for Raspberry Pi and other arm based boards

### ISSUE THREAD

**Issue by Links2004** [kubernetes-csi/livenessprobe#130]
I am currently running a mixed cluster with armv7 and amd64 nodes.
the csi is running fine for the amd64 but the armv7 nodes have a ImagePullBackOff since there is only a arm64 and amd64 build and no armv7 build.

This issue related to, since the project uses:
- kubernetes-csi/livenessprobe
- kubernetes-csi/csi-node-driver-registrar

https://github.com/kubernetes-csi/csi-driver-smb/issues/346

**Comment by mauriciopoppe** [comment]
/remove-lifecycle rotten

Support for arm/v7 was recently added in https://github.com/kubernetes-csi/livenessprobe/pull/139, I checked the staging images and the manifest has the arm v7 version

```
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 738,
         "digest": "sha256:a18a09ebbf83276356d2848d8833ad25b325de338676db03642796ec08f8e483",
         "platform": {
            "architecture": "arm",
            "os": "linux",
            "variant": "v7"
         }
      },
```

I'll update this issue once we have the image in the release registry

**Comment by mauriciopoppe** [comment]
sorry to get back to this so late, we actually released armv7 support back in https://github.com/kubernetes-csi/livenessprobe/releases/tag/v2.6.0 which was around February
