### ISSUE TITLE
When is the next release 2.5?

### ISSUE THREAD

**Issue by msjingli** [kubernetes-csi/livenessprobe#132]
When is the next release 2.5? Need the update to support Windows Server 2022. Thanks!

**Comment by andyzhangx** [comment]
> @msjingli @andyzhangx would you be able to help confirm the ltsc2022 staging canary images are working as expected in a cluster?
> 
> https://console.cloud.google.com/gcr/images/k8s-staging-sig-storage/global/livenessprobe@sha256:3660ab76b4d6ca6f834f089c621107e04f512309eada77703006ac5f040c3e32/details
> 
> https://console.cloud.google.com/gcr/images/k8s-staging-sig-storage/global/csi-node-driver-registrar@sha256:306173ebbf30db1113299386458da46a259692e2c137cea39d791eb151f01c2f/details
> 
> cc @mauriciopoppe

@verult thanks, I have verified that image `gcr.io/k8s-staging-sig-storage/livenessprobe:amd64-windows-nanoserver-ltsc2022-canary` works well in ltsc2022 Windows node.

**Comment by verult** [comment]
The multi-arch k8s.gcr.io/sig-storage/livenessprobe:v2.5.0 is now available. The ltsc2022 image hash is 437449b320e2ed96a679c1e001fcbceb11a12bcf1f91d10beafdb128901a4988

**Comment by andyzhangx** [comment]
@verult thanks, could you also cut v2.4.0 release in https://github.com/kubernetes-csi/node-driver-registrar?

**Comment by verult** [comment]
node-driver-registrar is waiting for this PR to be resolved: https://github.com/kubernetes-csi/node-driver-registrar/pull/171

Hopefully the remaining change shouldn't be too big. If you need it more urgently I can reach out to the PR author to consider it for the next release.

**Comment by verult** [comment]
The multi-arch k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.4.0 is now available. The ltsc2022 image hash is a265945ae13ac8d88844df99b92145c4dd06eeade006aaf7244a5cedf8d251b7

@msjingli @andyzhangx could you help verify this release works on ltsc2022?

**Comment by andyzhangx** [comment]
Thanks, I have verified the two sidecar containers work well on ltsc2022. Close this issue now.
