### ISSUE TITLE
Support structured logging

### ISSUE THREAD

**Issue by jcogilvie** [kubernetes-csi/livenessprobe#165]
The `livenessprobe` container should support structured logging when given the `--log-format-json` flag, like for instance the `secrets-store-csi-driver` does.

A simple implementation can be found here:  https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/main/cmd/secrets-store-csi-driver/main.go#L90-L94

**Comment by Kartik494** [comment]
I would like to give a try on this.
/assign

**Comment by mauriciopoppe** [comment]
@Kartik494 there's more info here too about kubernetes components https://github.com/kubernetes-csi/node-driver-registrar/issues/228#issuecomment-1281453724

**Comment by Kartik494** [comment]
@mauriciopoppe Thanks for the guidance i will take a look.

**Comment by bells17** [comment]
Hi @Kartik494 and @mauriciopoppe !

I hope this message finds you well. Is the development for the PR related to this issue, linked below, still ongoing?
https://github.com/kubernetes-csi/livenessprobe/pull/168

I noticed that there hadn't been any recent commits, so I took the liberty of creating a new PR, which you can find here:
https://github.com/kubernetes-csi/livenessprobe/pull/202.

If development on the above PR has stopped, I would appreciate it if you would take a moment to review my PR.
Thanks for your time and consideration.
