### ISSUE TITLE
Unable to run Livenessprobe sidecar yaml

### ISSUE THREAD

**Issue by Kartik494** [kubernetes-csi/livenessprobe#167]
When  i am trying to run [liveness probe sidecar yaml](https://github.com/kubernetes-csi/livenessprobe/blob/master/deployment/kubernetes/livenessprobe-sidecar.yaml)  getting below error:

`kubectl apply -f livenessprobe-sidecar.yaml 
error: error parsing livenessprobe-sidecar.yaml: error converting YAML to JSON: yaml: line 22: did not find expected '-' indicator`
https://github.com/kubernetes-csi/livenessprobe/blob/4d2afd41b8e15337490ad7c980012575f5646aba/deployment/kubernetes/livenessprobe-sidecar.yaml#L22 

But in line number 22 i found # only.

Kubernetes version : v1.25

**Comment by Kartik494** [comment]
Hi @mauriciopoppe Would you mind to take a look here .

**Comment by mauriciopoppe** [comment]
that example has a section https://github.com/kubernetes-csi/livenessprobe/blob/4d2afd41b8e15337490ad7c980012575f5646aba/deployment/kubernetes/livenessprobe-sidecar.yaml?rgh-link-date=2022-10-19T08%3A02%3A50Z#L44-L52 on how the livenessprobe should be added to the CSI Driver node deployment, see this for a complete example: 

https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/a273606566f5572fc493cf15f93946f7706ad2ff/deploy/v1.23.0/csi-azuredisk-node.yaml#L38-L53

**Comment by Kartik494** [comment]
Thanks @mauriciopoppe i am closing this issue in reference to comment  https://github.com/kubernetes-csi/livenessprobe/issues/167#issuecomment-1285927187
