### ISSUE TITLE
Facing vulnerability issues with golang, net

### ISSUE THREAD

**Issue by kalpanathanneeru21** [kubernetes-csi/livenessprobe#180]
Facing vulnerability issues with golang, net since these are outdated/older

			

  |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | --
  |   |   | livenessprobe/6233d3ca658768ca9c3 9e8ad55f01f84adff930c/sha256__32ca3d8516d3b0 cd0311d54a49ea0616f4964c49e38b23f1d88f215e9 3fe1b7d.tar.gz/livenessprobe/golang.org/x/net | golang.org/x/net | < 0.7.0 | 0.7.0 | 2023-03-10T03:31:0 4Z
  |   |   |   |   |   |   |  
  |   |   |   |   |   |   |  

current env:
k8s.gcr.io/sig-storage/livenessprobe: 2.9.0
EKS 1.22

are there upcoming releases are going have fixes for these vulnerabilities

**Comment by jsafrane** [comment]
this has been fixed in v2.10.0
