### ISSUE TITLE
Upgrade livenessprobe to use Debian 12 Distroless

### ISSUE THREAD

**Issue by jhawkins1** [kubernetes-csi/livenessprobe#267]
Since Debian 12 Distroless is available, as well as, the latest releases of Kubernetes and many of the Kubernetes related projects have moved to Debian 12, we would request that livenessprobe move to Debian 12 Distroless to align with other Kubernetes components.

Benefits: Alignment of the Container OS being used to other Kubernetes Components and related Projects. Reduces fan-out of multiple OSes or different versions of OSes across components. Potential benefits as to being able to obtain OS patches for vulnerabilities where Debian has decided only to fix in latest LTS (Debian 12) release and not older LTS releases.

**Comment by kady1711** [comment]
Inquire about the progress on migrating `livenessprobe` to Debian 12 Distroless, as previously discussed. This update is crucial for ensuring alignment with the broader Kubernetes ecosystem, which has largely transitioned to Debian 12. The move is expected to streamline our operations, particularly in terms of managing OS patches for vulnerabilities that Debian has committed to addressing in its latest LTS release only.

Could you please provide an update on this migration? Specifically, it would be immensely helpful to know the **targeted release date or version number** by which this change is expected to be implemented.

This information will be invaluable for our planning and operational readiness, ensuring we can maintain a secure and consistent deployment environment.

**Comment by sdx-jkataja** [comment]
It appears the `gcr.io/distroless/static:latest`  base image has already changed to Debian 12. 
The change has taken place some time in between the versions:

 - v2.12.0 is based on Debian 11
 - v2.13.1 is based on Debian 12
