### ISSUE TITLE
livenessproble 2.13.0 image pull not working

### ISSUE THREAD

**Issue by chethanv28** [kubernetes-csi/livenessprobe#273]
Observing the below error while attempting to pull latest release of csi-livenessprobe

```
Error response from daemon: manifest for registry.k8s.io/sig-storage/livenessprobe:v2.13.0 not found: manifest unknown: Failed to fetch "v2.13.0"
```

**Comment by xing-yang** [comment]
Microsoft has broken their base container images, https://github.com/microsoft/Windows-Containers/issues/493
We can't build Windows images.

**Comment by jbg** [comment]
Getting the same error when trying to pull a Linux image

**Comment by luhi-DT** [comment]
It looks like https://github.com/microsoft/Windows-Containers/issues/493 is fixed, at least according to the issue, is it now possible to release the images? :)

**Comment by jsafrane** [comment]
This has been fixed, please pull `registry.k8s.io/sig-storage/livenessprobe:v2.13.1`
/close
