### ISSUE TITLE
support exec style liveness probes in addition to http

### ISSUE THREAD

**Issue by travisghansen** [kubernetes-csi/livenessprobe#82]
I have scenarios where either or both of the `node` and `controller` services run in the `hostNetwork` namespace. Combined with the possibility of multiple deployments it means I need to eat through host ports (and reserve them) which is less than ideal.

What would be great is an ability to use the `exec` style probes and simply have the app connect to the uds and exit as appropriate.

**Comment by jsafrane** [comment]
The way we use liveness probes in CSI drivers is that the liveness sidecar exposes a port, but the actual liveness probe is run against the driver container. If the check fails, the *driver* container is killed and restarted.

Is it possible with exec probe? If the livenesprobe binary is in a sidecar with container liveness exec probe, only the sidecar gets restarted, which is not really useful.

@travisghansen, do you have any better idea?

**Comment by travisghansen** [comment]
@jsafrane You are correct. My thinking was that the project could include pre-built binaries as well as the images so if someone wanted to inject the binary straight into the driver container they could.

Having said that I ended up creating a little script inside my containers which replicated the functionality of this project but in exec style invocation. This was easy enough but not ideal if the logic ever gets more complicated etc.

**Comment by msau42** [comment]
I saw this project recently: https://github.com/grpc-ecosystem/grpc-health-probe

But I think the problem is it requires the csi plugin to use a grpc specific health probe call, instead of the custom csi probe call we have.

**Comment by travisghansen** [comment]
https://github.com/democratic-csi/democratic-csi/blob/master/bin/liveness-probe

What I did...obviously not ideal for drivers not built in nodejs.
