### ISSUE TITLE
Support ARM Images?

### ISSUE THREAD

**Issue by kferrone** [kubernetes-csi/livenessprobe#89]
I recently opened a request with `kubernetes-csi/csi-driver-smb` to support ARM. They did and pushed the image. Now this project needs the same. 
Here are the related issues and PRs:
 - https://github.com/kubernetes-csi/csi-driver-smb/issues/138#event-3978326534
 - https://github.com/kubernetes-csi/csi-driver-smb/pull/144

My end goal is to use the chart within smb-csi repo which also uses this projects image.

**Comment by msau42** [comment]
Our build infra already supports multi arch images. We just need to release a new version of livenessprobe.

@jsafrane can you help prepare a release?

**Comment by kferrone** [comment]
Well that's good news! I'll keep an eye out

**Comment by msau42** [comment]
Actually, can you try this image? k8s.gcr.io/sig-storage/livenessprobe:v2.1.0 should already be built for arm

**Comment by kferrone** [comment]
I have tried and it works! Thanks a bunch.

**Comment by msau42** [comment]
Great!

/close
